export { WealthManagementAgent } from './WealthManagementAgent';
export { wealthManagementManifest } from './manifest';
export type {
  WealthManagementConfig,
  Portfolio,
  PortfolioAsset,
  TargetAllocation,
  CurrentAllocation,
  PortfolioPerformance,
  BenchmarkComparison,
  FinancialPlan,
  FinancialGoal,
  FinancialSituation,
  IncomeInfo,
  IncomeSource,
  ExpenseInfo,
  ExpenseCategory,
  AssetInfo,
  LiabilityInfo,
  InsuranceInfo,
  Recommendation,
  FinancialProjection,
  YearlyProjection,
  ProjectionAssumption,
  MarketAnalysis,
  MarketInsight,
  MarketRecommendation,
  MarketData,
  MarketIndicator,
  MarketTrend,
  CorrelationMatrix,
  VolatilityData,
  RiskFactor
} from './WealthManagementAgent';