name: Documentation

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths: 
      - 'docs/**'
      - '**.md'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'docs/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd docs
        npm ci
        
    - name: Build documentation
      run: |
        cd docs
        npm run build
        
    - name: Test documentation
      run: |
        cd docs
        npm run test
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build
        destination_dir: docs
        
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v3
      with:
        name: documentation-build
        path: docs/build/
